### ISSUE TITLE
Altus v4.0

### ISSUE THREAD

**Issue by amanharwara** [amanharwara/altus#49]
Recently, I've been trying to work on bug fixes and new features, but it has become very tedious since the code is very cluttered. So, I've decided that it would be good to start from scratch and build a major update.

I'll try to fix bugs before I start working on v4.0 if they are urgent. But any feature request will not be added until v4.0.

This thread is to discuss the upcoming update. I'll list the things I have in mind below. Feel free to drop your own suggestions and anything that you want to discuss.

### ⚛ Switch to React

Switching to React will allow for less cluttered code in my opinion. I say this because it'll allow me to separate the code into components which will definitely improve readability and will allow for easier modifications. If you look at the UI, it will make a lot of sense to use components.

Although, the are definitely some concerns to using React. One of them is that it might bloat the app because of all the dependencies that will be required. I think this can be partially solved at least, by using tree-shaking.

I would definitely like some feedback on this aspect.

### 👓 Revamped UI w/ Accessibility features

You might notice that the UI is not consistent throughout. I intend to change this by creating a basic "design system" for the next version. Also, the UI will be more accessible and user-friendly by following WCAG guidelines.

### Revamped Tabs

I think the tab system could definitely use a revamp. Especially re-arrangement. Currently you can't drag and drop tabs to re-arrange them. Also would be better to align the tab hotkeys to browser tab hotkeys as users will be more familiar with those hotkeys.

### ⚙ Import/Export/Restore Settings

It would be good to implement some kind of import/export system for the settings, also the ability to restore to the defaults. The current settings system doesn't have any of these.
This would probably require changing how the settings are structured currently, but it will be worth it.

### ⬇ Downloads History

A separate tab for storing a history of downloads. Similar to the "Downloads" area in browsers like Chrome & Firefox.
This history will be stored locally so there aren't any privacy concerns. The benefit of this will be that you'll easily be able to re-download the file without having to go back to that specific chat.

----

## See [this comment](https://github.com/amanharwara/altus/issues/49#issuecomment-595683788) for the to-do list.

**Comment by amanharwara** [comment]
## To-Do (Follow branch [`v4.0`](https://github.com/amanharwara/altus/tree/v4.0) for commits)
- [x] Set-up Electron with React, Typescript & SASS using electron-forge.
- [ ] Set-up correct folder structure for components, styles, utility files, etc.
- [ ] Create new tabbing system.
  - [ ] Make sure tabs follow browser-like keyboard shortcuts.
  - [ ] Vertical/horizontal alignment for tab bar.
  - [ ] Show/hide tab bar.
  - [ ] Re-arrange tabs.
  - [ ] Tab settings should open in a pop-up instead of a full modal.
- [ ] Set up theming system.
- [ ] Improve the settings system.
  - [ ] Set up settings query with defaults.
  - [ ] Add import/export feature.
  - [ ] Add reset settings feature.
  - [ ] Set up checks to see if a setting exists and non-obstructively add it if it doesn't.
- [ ] Create download history system.
- [ ] Make interface keyboard-friendly.
  - [ ] Set up vim-like keyboard shortcuts for links, buttons, etc inside WhatsApp instances. This setting should be toggle-able.

**Comment by amanharwara** [comment]
I'm stopping work on v4.0 for now. I've been having issues with the WebView component. I haven't been able to find any fix for it, which is a big block to the development. Unless I can find any fix for it, I'll only be working on v3.x.

It's hard to explain what the actual issue with the WebView is. If you think you might know how to fix it, go to the [v4.0](https://github.com/amanharwara/altus/tree/v4.0) branch and make the changes necessary and let me know if it works.

**Comment by marab2** [comment]
Hi Aman,
You are doing amazing thing, we really do appreciate your efforts. I hope to see a very important feature in the upcoming release which is freeze chat list when sending messages to people, sometimes we need to send a couple of contact messages and they are in the bottom down, when we send one we need to go back again to the same place with the scroller to find them and resend. When you do something to stop/disable the "WhatsAPP WEB autoscrolling" this will be helpful for too many people

**Comment by jnntin** [comment]
I want to use altus with one proxy connection per account (socks5 or http proxy), can you help me achieve this?
